version: "3.7"

services:
  nginx_coffe_shop:
    image: nginx:latest
    container_name: nginx_coffe_shop
    ports:
      - "81:80"
    volumes:
      - ./project:/var/www/html/website:rw # With read / write access
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro # With read-only access
    networks:
      - lemp-network
    depends_on:
      - php_coffe_shop

  mariadb_coffe_shop:
    image: mariadb:latest
    container_name: mariadb_coffe_shop
    volumes:
      - ./lemp-volume-mariadb:/var/lib/mysql
    networks:
      - lemp-network
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: coffe_db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_coffe_shop
    networks:
      - lemp-network
    ports:
      - "8186:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
    depends_on:
      - mariadb_coffe_shop

  php_coffe_shop:
    build: ./
    container_name: php_coffe_shop
    volumes:
      - ./project:/var/www/html/website
      - ./custom.php.ini:/usr/local/etc/php/php.ini
    networks:
      - lemp-network
    depends_on:
      - mariadb_coffe_shop

networks:
  lemp-network:
    driver: bridge
